#!/bin/python3

import sys

def solve(grades):
    answer=[]
    for x in grades:
        if x > 37:
            if x%5 == 3:
                x=x+2
            if x%5 == 4:
                x=x+1
        answer.append(x)
    return answer


n = int(input().strip())
grades = []
grades_i = 0
for grades_i in range(n):
   grades_t = int(input().strip())
   grades.append(grades_t)
result = solve(grades)
print ("\n".join(map(str, result)))